package com.utilityservice.serviceplans.service.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-19T11:22:32.129-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://service.serviceprovider.bootcamp.com/", name = "CustomerServiceProvider")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerServiceProvider {

    @WebMethod
    @RequestWrapper(localName = "getServiceById", targetNamespace = "http://service.serviceprovider.bootcamp.com/", className = "com.utilityservice.serviceplans.service.soapclient.GetServiceById")
    @ResponseWrapper(localName = "getServiceByIdResponse", targetNamespace = "http://service.serviceprovider.bootcamp.com/", className = "com.utilityservice.serviceplans.service.soapclient.GetServiceByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.utilityservice.serviceplans.service.soapclient.PlanInfo> getServiceById();
}
