package com.utilityservice.serviceplans.service.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-19T11:22:32.138-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "ServiceProvider", 
                  wsdlLocation = "file:/C:/BCJMay16/Develop/GitRepo/CustomerUtilityService/src/main/resources/soapWSDL.wsdl",
                  targetNamespace = "http://service.serviceprovider.bootcamp.com/") 
public class ServiceProvider extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.serviceprovider.bootcamp.com/", "ServiceProvider");
    public final static QName CustomerServiceProviderImplPort = new QName("http://service.serviceprovider.bootcamp.com/", "CustomerServiceProviderImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/BCJMay16/Develop/GitRepo/CustomerUtilityService/src/main/resources/soapWSDL.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceProvider.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/BCJMay16/Develop/GitRepo/CustomerUtilityService/src/main/resources/soapWSDL.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceProvider(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceProvider(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceProvider() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ServiceProvider(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiceProvider(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiceProvider(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CustomerServiceProvider
     */
    @WebEndpoint(name = "CustomerServiceProviderImplPort")
    public CustomerServiceProvider getCustomerServiceProviderImplPort() {
        return super.getPort(CustomerServiceProviderImplPort, CustomerServiceProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerServiceProvider
     */
    @WebEndpoint(name = "CustomerServiceProviderImplPort")
    public CustomerServiceProvider getCustomerServiceProviderImplPort(WebServiceFeature... features) {
        return super.getPort(CustomerServiceProviderImplPort, CustomerServiceProvider.class, features);
    }

}
